# This file was generated by GoReleaser. DO NOT EDIT.
cask "tome" do
  name "tome"
  desc "AI Agent Skill Manager - Your spellbook for AI agent capabilities"
  homepage "https://github.com/kennyg/tome"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tome"

  on_macos do
    on_intel do
      url "https://github.com/kennyg/tome/releases/download/v#{version}/tome_#{version}_darwin_amd64.tar.gz"
      sha256 "08ced7c59e4a78891357b8c41bf25f1130d44bb4d858d943364bf782e70a6a7a"
    end
    on_arm do
      url "https://github.com/kennyg/tome/releases/download/v#{version}/tome_#{version}_darwin_arm64.tar.gz"
      sha256 "4091f1e8de4fd2fd4b70b34aa48343c53ea70fd1007648e472e7c3c8338fdb8b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kennyg/tome/releases/download/v#{version}/tome_#{version}_linux_amd64.tar.gz"
      sha256 "0a086ef01e054c654fff1ed32b030402a32ecd2f941ded7ab11820b3249efa15"
    end
    on_arm do
      url "https://github.com/kennyg/tome/releases/download/v#{version}/tome_#{version}_linux_arm64.tar.gz"
      sha256 "53d7067bf385eb4aaabd9a1b0ed191354375a1043da88fe1d4ed8fc442a0be53"
    end
  end

  # No zap stanza required
end
