# This file was generated by GoReleaser. DO NOT EDIT.
cask "tome" do
  name "tome"
  desc "AI Agent Skill Manager - Your spellbook for AI agent capabilities"
  homepage "https://github.com/kennyg/tome"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tome"

  on_macos do
    on_intel do
      url "https://github.com/kennyg/tome/releases/download/v#{version}/tome_#{version}_darwin_amd64.tar.gz"
      sha256 "5ffffe0e2159b5c4fe3f143eea61341d5dd9119d255c2cb43feb5f5380250ed6"
    end
    on_arm do
      url "https://github.com/kennyg/tome/releases/download/v#{version}/tome_#{version}_darwin_arm64.tar.gz"
      sha256 "efafecdbe30df5070f6d6cb4d03afc7d3c22b0c03b2aa16044d662c0b54e1da0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kennyg/tome/releases/download/v#{version}/tome_#{version}_linux_amd64.tar.gz"
      sha256 "8d43c5294e60e8a8daa53b4b1b4031fa67aaaa815f0d41b21a384eccb16d05a4"
    end
    on_arm do
      url "https://github.com/kennyg/tome/releases/download/v#{version}/tome_#{version}_linux_arm64.tar.gz"
      sha256 "29c0e5d2fe458f4f8e06342b2b2bae2b565b1b560c485fd57b175128ca33cb3a"
    end
  end

  # No zap stanza required
end
