# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tome < Formula
  desc "Your spellbook for AI agent capabilities. Discover, install, and manage skills, commands, and prompts."
  homepage "https://github.com/kennyg/tome"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kennyg/tome/releases/download/v0.6.2/tome_0.6.2_darwin_amd64.tar.gz"
      sha256 "d16aa0a0122e9e6b806bfd8b0cc2568e3bb55536b8e38de6f951e0e9b511baca"

      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kennyg/tome/releases/download/v0.6.2/tome_0.6.2_darwin_arm64.tar.gz"
      sha256 "ece9862d696a3c8a0c07076ba263f546d9e3b047b92f57bc77640923d588bd97"

      def install
        bin.install "tome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennyg/tome/releases/download/v0.6.2/tome_0.6.2_linux_amd64.tar.gz"
      sha256 "a3782fd046407faf1368d0422964da9a07c88fc1dfcb06510ef323134c06fac9"
      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennyg/tome/releases/download/v0.6.2/tome_0.6.2_linux_arm64.tar.gz"
      sha256 "df8b71b490cfea17ae5170aa4ab376381d0a77848895151fe1f31f869ecec05d"
      def install
        bin.install "tome"
      end
    end
  end

  test do
    system "#{bin}/tome", "edition"
  end
end
