# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tome < Formula
  desc "Your spellbook for AI agent capabilities. Discover, install, and manage skills, commands, and prompts."
  homepage "https://github.com/kennyg/tome"
  version "0.12.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kennyg/tome/releases/download/v0.12.5/tome_0.12.5_darwin_amd64.tar.gz"
      sha256 "7e7d2723e4a57102440bc8c4a49121aa3c6edd00400fe19450dbe4c9462be0fa"

      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kennyg/tome/releases/download/v0.12.5/tome_0.12.5_darwin_arm64.tar.gz"
      sha256 "808157ff72a5f23a6ac428ac8af3965e417b5b665fa1edde307a9f25716fcc01"

      def install
        bin.install "tome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennyg/tome/releases/download/v0.12.5/tome_0.12.5_linux_amd64.tar.gz"
      sha256 "e07def3ea82f372a8feb0ac553c8b97fb0c434bae2fcf74393fc658f0bfa7e2b"
      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennyg/tome/releases/download/v0.12.5/tome_0.12.5_linux_arm64.tar.gz"
      sha256 "865c1a160ccce983fb1716b5a521f1bf36f27f74ce620d1f559865c2d7ee13c3"
      def install
        bin.install "tome"
      end
    end
  end

  test do
    system "#{bin}/tome", "edition"
  end
end
