# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tome < Formula
  desc "Your spellbook for AI agent capabilities. Discover, install, and manage skills, commands, and prompts."
  homepage "https://github.com/kennyg/tome"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kennyg/tome/releases/download/v0.10.0/tome_0.10.0_darwin_amd64.tar.gz"
      sha256 "69ff66bf13b7a9cd41ea0dbcaf259f207347e4ca9e9c0f01684529890b58bb26"

      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kennyg/tome/releases/download/v0.10.0/tome_0.10.0_darwin_arm64.tar.gz"
      sha256 "e349cfdfa9fd09275c7aa84aba1b8b7b05522212ee2c271de858ab505714c1b3"

      def install
        bin.install "tome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennyg/tome/releases/download/v0.10.0/tome_0.10.0_linux_amd64.tar.gz"
      sha256 "d75526ead6c4906bad5674b63123826b099d2c871b81a5036f9b202e22b26aae"
      def install
        bin.install "tome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennyg/tome/releases/download/v0.10.0/tome_0.10.0_linux_arm64.tar.gz"
      sha256 "0fb60df853aa8c8061bc8060f3cc05329eda27300d853644c1dac4a9246a3cb0"
      def install
        bin.install "tome"
      end
    end
  end

  test do
    system "#{bin}/tome", "edition"
  end
end
